module.exports = {
  "indent": [2, 2],
  "no-script-url": [0],
  "no-case-declarations": [0],
  "import/first": [0],
  "class-methods-use-this": 0,
  "no-continue": [0],
  "no-plusplus": [0],
  "no-console": [2],
  "guard-for-in": [0],
  "one-var": [0],
  "no-trailing-spaces": [0],
  "array-callback-return": [0],
  "arrow-parens": [1, "as-needed", { "requireForBlockBody": true }],
  "react/sort-comp": [0],
  "prefer-destructuring": [0],
  "prefer-template": "off",
  "generator-star-spacing": [0],
  "no-param-reassign": [0],
  "consistent-return": [0],
  "global-require": [0],
  "import/prefer-default-export": [0],
  "no-unused-expressions": [0],
  "no-else-return": [1],
  "no-restricted-syntax": [0],
  "import/no-extraneous-dependencies": [0],
  "import/no-dynamic-require": [0],
  "no-use-before-define": [0],
  "no-nested-ternary": [0],
  "arrow-body-style": [0],
  "import/extensions": [0],
  "no-bitwise": [0],
  "no-cond-assign": [0],
  "import/no-unresolved": [0],
  "comma-dangle": ["error", {
    "arrays": "always-multiline",
    "objects": "always-multiline",
    "imports": "always-multiline",
    "exports": "always-multiline",
    "functions": "ignore"
  }],
  "object-curly-newline": [0],
  "function-paren-newline": [0],
  "no-restricted-globals": [0],
  "require-yield": [1]
}
